# Generated by Django 4.2.7 on 2026-01-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_locked_initial_funding'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exchange',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False)), fields=('name',), name='unique_exchange_name_case_insensitive'),
        ),
    ]
