# Generated by Django 4.2.7 on 2026-01-11 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientexchangeaccount',
            name='my_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Your total percentage share (0-100, decimals allowed) - DEPRECATED: Use loss_share_percentage and profit_share_percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='clientexchangereportconfig',
            name='friend_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Friend/Student percentage (report only, decimals allowed)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='clientexchangereportconfig',
            name='my_own_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Your own percentage (report only, decimals allowed)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('FUNDING_MANUAL', 'Funding'), ('FUNDING_AUTO', 'Auto Re-Funding'), ('TRADE', 'Trade'), ('SETTLEMENT_SHARE', 'Settlement Share Payment'), ('FEE', 'Fee'), ('ADJUSTMENT', 'Adjustment'), ('FUNDING', 'Funding (Legacy)'), ('RECORD_PAYMENT', 'Record Payment')], max_length=20),
        ),
    ]
