# Generated by Django 4.2.27 on 2026-01-14 09:34

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_exchange_version'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exchange',
            name='unique_exchange_name_case_insensitive',
        ),
        migrations.AddConstraint(
            model_name='exchange',
            constraint=models.UniqueConstraint(
                fields=('name', 'version'),
                name='unique_exchange_name_version',
            ),
        ),
    ]
