# Generated by Django 4.2.27 on 2026-01-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_update_exchange_unique_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exchange',
            name='unique_exchange_name_version',
        ),
        migrations.AlterField(
            model_name='exchange',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='exchange',
            constraint=models.UniqueConstraint(fields=('name', 'code', 'version'), name='unique_exchange_name_code_version'),
        ),
    ]
